server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_oauth2
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

feign:
  hystrix:
    enabled: true