eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: oauth-hi
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_oauth2_demo
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
oauth2.baseuri: /uaa
security:
  oauth2:
    resource:
      user-info-uri: ${oauth2.baseuri}/users/current
    client:
      client-id: service-hi
      client-secret: 123456
      access-token-uri: ${oauth2.baseuri}/oauth/token
      grant-type: client_credentials,password
      scope: server
